.TH FIXWORLD 1
.SH NAME
fixworld \- fix what's wrong in the world
.SH SYNOPSIS
.B fixworld
[\fB\-i\fR]
[\fB\--interactive\fR]
.SH DESCRIPTION
.B fixworld
fixes everything that is wrong in this world.
.SH OPTIONS
.TP
.BR \-i ", " \-\-interactive\fR
Ask for confirmation before fixing anything wrong. Can take a lot of time.
